const quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "Get busy living or get busy dying. - Stephen King",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Whether you think you can or you think you can't, you're right. - Henry Ford",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "That which does not kill us makes us stronger. - Friedrich Nietzsche",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "Dream big and dare to fail. - Norman Vaughan",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "The best way to predict the future is to invent it. - Alan Kay",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Act as if what you do makes a difference. It does. - William James",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
    "Life isn't about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    "Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "Limit your 'always' and your 'nevers'. - Amy Poehler",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "It is never too late to be what you might have been. - George Eliot",
    "The best time to plant a tree was twenty years ago. The second best time is now. - Chinese Proverb",
    "If you can dream it, you can do it. - Walt Disney",
    "Your life does not get better by chance, it gets better by change. - Jim Rohn",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
    "The best revenge is massive success. - Frank Sinatra",
    "Dream as if you’ll live forever. Live as if you’ll die today. - James Dean",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "You can’t use up creativity. The more you use, the more you have. - Maya Angelou",
    "Don't count the days, make the days count. - Muhammad Ali",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "Everything has beauty, but not everyone sees it. - Confucius",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "Life is what we make it, always has been, always will be. - Grandma Moses",
    "The mind is everything. What you think you become. - Buddha",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "We don’t see things as they are, we see them as we are. - Anaïs Nin",
    "It’s not what happens to you, but how you react to it that matters. - Epictetus",
    "Keep your eyes on the stars, and your feet on the ground. - Theodore Roosevelt",
    "What we think, we become. - Buddha",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Everything you can imagine is real. - Pablo Picasso",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "You can’t build a reputation on what you are going to do. - Henry Ford",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Dream big and dare to fail. - Norman Vaughan",
    "Life is either a great adventure or nothing. - Helen Keller",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Your limitation—it's only your imagination. - Unknown",
    "Push yourself, because no one else is going to do it for you. - Unknown",
    "Great things never come from comfort zones. - Unknown",
    "Dream it. Wish it. Do it. - Unknown",
    "Success doesn’t just find you. You have to go out and get it. - Unknown",
    "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
    "Don’t stop when you’re tired. Stop when you’re done. - Unknown",
    "Wake up with determination. Go to bed with satisfaction. - Unknown",
    "Do something today that your future self will thank you for. - Unknown",
    "Little things make big days. - Unknown",
    "It’s going to be hard, but hard does not mean impossible. - Unknown",
    "Don’t wait for opportunity. Create it. - Unknown",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths. - Unknown"
];



const btn = document.getElementById("btn")
const quote = document.getElementById("quote")

btn.addEventListener("click", (e)=> {
        e.preventDefault()
        const rand = Math.floor(Math.random() *86)
        console.log(rand)
        item = quotes[rand]
        
        quote.textContent = item
})

